---
all:
  hosts:
    jenkins-master:
      ansible_host: 51.250.26.129
    jenkins-agent:
      ansible_host: 51.250.25.54
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master:
        jenkins_agents:
          hosts:
              jenkins-agent:
  vars:
    ansible_connection: ssh
    ansible_user: nprovorkova