services:
  dbpostgres:
    image: postgres:12
    container_name: postgres
    volumes:
      - first-postgres-volume:/var/lib/postgresql/data
      - second-postgres-volume:/backup
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pgdb
volumes:
  first-postgres-volume:
    external: true
  second-postgres-volume:
    external: true