---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: back
  namespace: stage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
      - image: provorkova/kubernetes-config_backend:latest

