---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - image: provorkova/kubernetes-config_frontend:latest
