---
apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
  namespace: prod
spec:
  type: NodePort
  selector:
    app: front
  ports:
    - port: 8000
      targetPort: 38800
      protocol: TCP