---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolit
  namespace: stage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: monolit
  template:
    metadata:
      labels:
        app: monolit
    spec:
      containers:
      - image: provorkova/kubernetes-config_backend:latest
        name: back
        ports:
        - containerPort: 9000
      - image: provorkova/kubernetes-config_frontend:latest
        name: front
        ports:
        - containerPort: 80
