---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: stage
spec:
  type: ClusterIP
  selector:
    app: postgresql
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: inner-stage
  namespace: stage
spec:
  ports:
    - name: web
      port: 80
    - name: api
      port: 9000
  selector:
    app: monolit
  type: ClusterIP