---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: stage
spec:
  type: ClusterIP
  selector:
    app: postgresql
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: stage-service
  namespace: stage
spec:
  type: NodePort
  selector:
    app: monolit
  ports:
    - port: 8000
      targetPort: 38000
      protocol: TCP