---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: stage
spec:
  serviceName: postgresql
  replicas: 2
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      serviceAccountName: postgresql
      terminationGracePeriodSeconds: 10
      containers:
        - name: postgresql
          image: postgres:13-alpine
          env:
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: news
          ports:
            - name: postgresql
              protocol: TCP
              containerPort: 5432
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
          volumeMounts:
            - name: postgres
              mountPath: /var/lib/postgresql/data/pgdata
            - name: postgres.conf
              mountPath: /etc/postgres.conf