---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: back
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
      - image: provorkova/kubernetes-config_backend:latest
        name: back
        ports:
        - containerPort: 9000
        volumeMounts:
          - mountPath: "/dynamic"
            name: common-volume
        env:
          - name: DATABASE_URL
            value: postgres://postgres:postgres@postgres-service:5432/news
      volumes:
        - name: common-volume
          persistentVolumeClaim:
            claimName: dynamic-pvc

