---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dynamic-pvc
  namespace: prod
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
