---
apiVersion: v1
kind: Service
metadata:
  name: front-service
  namespace: prod
spec:
  type: ClusterIP
  selector:
    app: front
  ports:
    - port: 8000
      targetPort: 80
      protocol: TCP
