---
apiVersion: v1
kind: Service
metadata:
  name: back-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.backName }}
  ports:
    - port: {{ .Values.backPort }}
      targetPort: {{ .Values.backPort }}
      protocol: TCP
