---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.backName }}
  template:
    metadata:
      labels:
        app: {{ .Values.backName }}
    spec:
      containers:
      - image: {{ .Values.backImage }}:{{ .Values.backImageTag }}
        name: {{ .Values.backName }}
        ports:
        - containerPort: {{ .Values.backPort }}
        volumeMounts:
          - mountPath: "/dynamic"
            name: dynamic-volume
        env:
          - name: DATABASE_URL
            value: postgres://postgres:postgres@postgres-service:5432/news
      volumes:
        - name: dynamic-volume
          persistentVolumeClaim:
            claimName: dynamic-pvc

