---
apiVersion: v1
kind: Service
metadata:
  name: front-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.frontName }}
  ports:
    - port: {{ .Values.frontPort }}
      targetPort: 80
      protocol: TCP
