---
all:
  hosts:
    vm-1:
      ansible_host: 51.250.30.82
    vm-2:
      ansible_host: 51.250.22.50
  children:
    sonarqube:
      hosts:
        vm-1:
    nexus:
      hosts:
        vm-2:
    postgres:
      hosts:
        vm-1:
  vars:
    ansible_connection: ssh
    ansible_user: nprovorkova